In [2]:
x = [1,2,3]
y = [2,3,4]
ans = []
for a,b in zip (x,y):
    v = a + b
    ans.append(v)
print (ans)

[3, 5, 7]


In [3]:
x = [[1,2],[3,4]]
y = [[2,3],[4,5]]
ans = []
for a,b in zip (x,y):
    

[[1, 2, 2, 3], [3, 4, 4, 5]]


In [6]:
import numpy as np

In [7]:
x = np.array([1,2,3])
y = np.array([2,3,4])
print(x,'+',y,'=',x+y)
print(x,'-',y,'=',x-y)
print(x,'*',y,'=',x*y)
print(x,'/',y,'=',x/y)

[1 2 3] + [2 3 4] = [3 5 7]
[1 2 3] - [2 3 4] = [-1 -1 -1]
[1 2 3] * [2 3 4] = [ 2  6 12]
[1 2 3] / [2 3 4] = [0.5        0.66666667 0.75      ]


In [8]:
import numpy as np

In [11]:
x = np.array([[1,2],[3,4]])
y = np.array([[2,3],[4,5]])
print(x,y,x+y,sep="\n")

[[1 2]
 [3 4]]
[[2 3]
 [4 5]]
[[3 5]
 [7 9]]


In [12]:
# one dimension matrix
x = np.array ([1,2,3])
print(x,type (x),x.shape, x.ndim)
#two dimension matrix
x2 = np.array ([[1,2],[3,4]])
print(x2,type (x2),x2.shape, x2.ndim)

[1 2 3] <class 'numpy.ndarray'> (3,) 1
[[1 2]
 [3 4]] <class 'numpy.ndarray'> (2, 2) 2


In [15]:
#three dimension matrix
x3 = np.array ([[[1,2],[3,4]],[[5,6],[7,8]]])
print(x3, x3.shape, x3.ndim,x3.size)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] (2, 2, 2) 3 8


matrix generationinm numpy
- array() #basic
- arange () #range of values with gap
- linespace () #range of valiue with equal gap 
- logspace () #range of values with equal gap in log scale 
- zeros () #array with all zeros
- ones () #array with all ones
- eye () #identity matrix
- diag () #diagonal matrix
- random.rand() #random matrix of given shape from 0 to 1
- random.randn() #random matrix of given shape from -1 to 1
- random.randint() #random matrix of given shape from range

In [16]:
x = np.arange(10)
print(x)
x1 = np.arange(-10,11,.5)
print(x1)
x2 = np.arange(-np.pi,np.pi,2)
print(x2)
x3 = np.arange(1,15,2)
print(x3)

[0 1 2 3 4 5 6 7 8 9]
[-10.   -9.5  -9.   -8.5  -8.   -7.5  -7.   -6.5  -6.   -5.5  -5.   -4.5
  -4.   -3.5  -3.   -2.5  -2.   -1.5  -1.   -0.5   0.    0.5   1.    1.5
   2.    2.5   3.    3.5   4.    4.5   5.    5.5   6.    6.5   7.    7.5
   8.    8.5   9.    9.5  10.   10.5]
[-3.14159265 -1.14159265  0.85840735  2.85840735]
[ 1  3  5  7  9 11 13]


In [17]:
x =np.linspace(0,10,10)
print(x)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [19]:
z = np.zeros(10)
print(z)
z1 = np.zeros((2,3))
print(z1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [23]:
o = np.ones((4,5))
print(o)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [26]:
e = np.eye(50, dtype=int)
print(e)

[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]


In [27]:
np.random.rand(3,3)

array([[0.54305912, 0.50329279, 0.41084212],
       [0.36755043, 0.99424734, 0.52581279],
       [0.56939674, 0.38063559, 0.6404322 ]])

In [28]:
np.random.randn(3,3)

array([[ 1.46299328,  0.706222  , -2.47072275],
       [ 0.39365143, -0.0230522 ,  1.39733237],
       [-0.49569295,  1.25064547,  0.53674604]])

In [30]:
np.random.randint(11,12,(3,3))

array([[11, 11, 11],
       [11, 11, 11],
       [11, 11, 11]])

matrix operations